name = "JMC MTR Lets Play Server"
author = "Jake Vento (JMC Team)"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bf26e364d7dea9a21aed57df130b3bf7af435b8cfda58862f7033fa3ddada529"

[versions]
fabric = "0.16.10"
minecraft = "1.19.2"
